// Code generated by scripts/sdkcontract from pkg/graphql/public and the event registry. DO NOT EDIT.

package frameworks

import (
	publicv1 "github.com/Livepeer-FrameWorks/monorepo/pkg/proto/events/public/v1"
	"google.golang.org/protobuf/proto"
)

// publicEventMessages returns an empty payload message for each public event type.
var publicEventMessages = map[string]func() proto.Message{
	"account.suspended":          func() proto.Message { return &publicv1.AccountSuspended{} },
	"api_token.created":          func() proto.Message { return &publicv1.ApiTokenCreated{} },
	"api_token.revoked":          func() proto.Message { return &publicv1.ApiTokenRevoked{} },
	"billing.details_updated":    func() proto.Message { return &publicv1.BillingDetailsUpdated{} },
	"billing.invoice_created":    func() proto.Message { return &publicv1.InvoiceCreated{} },
	"billing.invoice_paid":       func() proto.Message { return &publicv1.InvoicePaid{} },
	"billing.payment_failed":     func() proto.Message { return &publicv1.PaymentFailed{} },
	"billing.topup_credited":     func() proto.Message { return &publicv1.TopupCredited{} },
	"clip.failed":                func() proto.Message { return &publicv1.ClipFailed{} },
	"clip.ready":                 func() proto.Message { return &publicv1.ClipReady{} },
	"clip.requested":             func() proto.Message { return &publicv1.ClipRequested{} },
	"custom_domain.failed":       func() proto.Message { return &publicv1.CustomDomainFailed{} },
	"custom_domain.verified":     func() proto.Message { return &publicv1.CustomDomainVerified{} },
	"multistream.status_changed": func() proto.Message { return &publicv1.MultistreamStatusChanged{} },
	"recording.failed":           func() proto.Message { return &publicv1.RecordingFailed{} },
	"recording.ready":            func() proto.Message { return &publicv1.RecordingReady{} },
	"recording.started":          func() proto.Message { return &publicv1.RecordingStarted{} },
	"recording.stopped":          func() proto.Message { return &publicv1.RecordingStopped{} },
	"stream.connected":           func() proto.Message { return &publicv1.StreamConnected{} },
	"stream.created":             func() proto.Message { return &publicv1.StreamCreated{} },
	"stream.deleted":             func() proto.Message { return &publicv1.StreamDeleted{} },
	"stream.idle":                func() proto.Message { return &publicv1.StreamIdle{} },
	"stream.key_rotated":         func() proto.Message { return &publicv1.StreamKeyRotated{} },
	"stream.live":                func() proto.Message { return &publicv1.StreamLive{} },
	"stream.updated":             func() proto.Message { return &publicv1.StreamUpdated{} },
	"upload.aborted":             func() proto.Message { return &publicv1.UploadAborted{} },
	"upload.completed":           func() proto.Message { return &publicv1.UploadCompleted{} },
	"upload.created":             func() proto.Message { return &publicv1.UploadCreated{} },
	"upload.failed":              func() proto.Message { return &publicv1.UploadFailed{} },
	"upload.ready":               func() proto.Message { return &publicv1.UploadReady{} },
}
