// Code generated by scripts/sdkcontract from pkg/graphql/public and the event registry. DO NOT EDIT.

package frameworks

// SDKVersion is the version of this SDK.
const SDKVersion = "0.1.0"

// SDKLine is the compatibility line of this SDK; under 0.x each minor version is its own line.
const SDKLine = "0.1"

// MinServerVersion is the oldest FrameWorks release this SDK line supports.
const MinServerVersion = "v0.3.11"

// operations lists every operation this SDK ships with the first release that serves it.
var operations = map[string]operationInfo{
	"AbortVodUpload":        {Kind: "mutation", Since: "v0.3.11"},
	"CompleteVodUpload":     {Kind: "mutation", Since: "v0.3.11"},
	"CreateClip":            {Kind: "mutation", Since: "v0.3.11"},
	"CreateDeveloperToken":  {Kind: "mutation", Since: "v0.3.11"},
	"CreatePushTarget":      {Kind: "mutation", Since: "v0.3.11"},
	"CreateSigningKey":      {Kind: "mutation", Since: "v0.3.11"},
	"CreateStream":          {Kind: "mutation", Since: "v0.3.11"},
	"CreateStreamKey":       {Kind: "mutation", Since: "v0.3.11"},
	"CreateVodUpload":       {Kind: "mutation", Since: "v0.3.11"},
	"DeleteClip":            {Kind: "mutation", Since: "v0.3.11"},
	"DeleteDVR":             {Kind: "mutation", Since: "v0.3.11"},
	"DeletePushTarget":      {Kind: "mutation", Since: "v0.3.11"},
	"DeleteStream":          {Kind: "mutation", Since: "v0.3.11"},
	"DeleteStreamKey":       {Kind: "mutation", Since: "v0.3.11"},
	"DeleteVodAsset":        {Kind: "mutation", Since: "v0.3.11"},
	"GetClip":               {Kind: "query", Since: "v0.3.11"},
	"GetDVRChapter":         {Kind: "query", Since: "v0.3.11"},
	"GetSigningKey":         {Kind: "query", Since: "v0.3.11"},
	"GetStream":             {Kind: "query", Since: "v0.3.11"},
	"GetTenantUsage":        {Kind: "query", Since: "v0.3.11"},
	"GetUsageAggregates":    {Kind: "query", Since: "v0.3.11"},
	"GetVodAsset":           {Kind: "query", Since: "v0.3.11"},
	"GetVodUploadStatus":    {Kind: "query", Since: "v0.3.11"},
	"ListArtifacts":         {Kind: "query", Since: "v0.3.11"},
	"ListDVRChapters":       {Kind: "query", Since: "v0.3.11"},
	"ListDeveloperTokens":   {Kind: "query", Since: "v0.3.11"},
	"ListPushTargets":       {Kind: "query", Since: "v0.3.11"},
	"ListSigningKeys":       {Kind: "query", Since: "v0.3.11"},
	"ListStreamKeys":        {Kind: "query", Since: "v0.3.11"},
	"ListStreams":           {Kind: "query", Since: "v0.3.11"},
	"ListUsageRecords":      {Kind: "query", Since: "v0.3.11"},
	"RefreshStreamKey":      {Kind: "mutation", Since: "v0.3.11"},
	"ResolveIngestEndpoint": {Kind: "query", Since: "v0.3.11"},
	"ResolveViewerEndpoint": {Kind: "query", Since: "v0.3.11"},
	"RevokeDeveloperToken":  {Kind: "mutation", Since: "v0.3.11"},
	"RevokeSigningKey":      {Kind: "mutation", Since: "v0.3.11"},
	"ServerInfo":            {Kind: "query", Since: "v0.3.11"},
	"SetPlaybackPolicy":     {Kind: "mutation", Since: "v0.3.11"},
	"StartDVR":              {Kind: "mutation", Since: "v0.3.11"},
	"StopDVR":               {Kind: "mutation", Since: "v0.3.11"},
	"TenantEvents":          {Kind: "subscription", Since: "v0.3.11"},
	"TestPlaybackAccess":    {Kind: "mutation", Since: "v0.3.11"},
	"UpdatePushTarget":      {Kind: "mutation", Since: "v0.3.11"},
	"UpdateStream":          {Kind: "mutation", Since: "v0.3.11"},
}
