// Code generated by sdk_go/tools/genclient from generated.go. DO NOT EDIT.

package frameworks

import (
	"context"
	"iter"
	"time"
)

// operationCalls calls every generated query and mutation function with the
// fixture's variables.
var operationCalls = map[string]operationCall{
	"AbortVodUpload": {AbortVodUpload_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return AbortVodUpload(ctx, c, arg[string](v, "uploadId"))
	}},
	"AcceptClusterInvite": {AcceptClusterInvite_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return AcceptClusterInvite(ctx, c, arg[string](v, "inviteToken"))
	}},
	"AcknowledgeIncident": {AcknowledgeIncident_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return AcknowledgeIncident(ctx, c, arg[string](v, "id"))
	}},
	"AddIncidentNote": {AddIncidentNote_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return AddIncidentNote(ctx, c, arg[string](v, "id"), arg[string](v, "body"))
	}},
	"ApplyClusterMediaConsentChange": {ApplyClusterMediaConsentChange_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ApplyClusterMediaConsentChange(ctx, c, arg[ApplyMediaCapacityConsentInput](v, "input"))
	}},
	"ApplyMediaPlacementChange": {ApplyMediaPlacementChange_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ApplyMediaPlacementChange(ctx, c, arg[ApplyMediaPlacementChangeInput](v, "input"))
	}},
	"ApproveClusterSubscription": {ApproveClusterSubscription_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ApproveClusterSubscription(ctx, c, arg[string](v, "subscriptionId"))
	}},
	"AssignIncident": {AssignIncident_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return AssignIncident(ctx, c, arg[string](v, "id"), arg[*string](v, "assigneeUserId"))
	}},
	"BootstrapEdge": {BootstrapEdge_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return BootstrapEdge(ctx, c, arg[BootstrapEdgeInput](v, "input"))
	}},
	"ChangeBillingTier": {ChangeBillingTier_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ChangeBillingTier(ctx, c, arg[string](v, "tierId"))
	}},
	"CompleteVodUpload": {CompleteVodUpload_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CompleteVodUpload(ctx, c, arg[CompleteVodUploadInput](v, "input"))
	}},
	"CreateCardTopup": {CreateCardTopup_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateCardTopup(ctx, c, arg[CreateCardTopupInput](v, "input"))
	}},
	"CreateClip": {CreateClip_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateClip(ctx, c, arg[CreateClipInput](v, "input"))
	}},
	"CreateClusterInvite": {CreateClusterInvite_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateClusterInvite(ctx, c, arg[CreateClusterInviteInput](v, "input"))
	}},
	"CreateConversation": {CreateConversation_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateConversation(ctx, c, arg[CreateConversationInput](v, "input"))
	}},
	"CreateCryptoTopup": {CreateCryptoTopup_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateCryptoTopup(ctx, c, arg[CreateCryptoTopupInput](v, "input"))
	}},
	"CreateDeveloperToken": {CreateDeveloperToken_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateDeveloperToken(ctx, c, arg[CreateDeveloperTokenInput](v, "input"))
	}},
	"CreateEdgeCluster": {CreateEdgeCluster_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateEdgeCluster(ctx, c, arg[CreateEdgeClusterInput](v, "input"))
	}},
	"CreateEnrollmentToken": {CreateEnrollmentToken_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateEnrollmentToken(ctx, c, arg[string](v, "clusterId"), arg[*string](v, "name"), arg[*string](v, "ttl"))
	}},
	"CreateMollieFirstPayment": {CreateMollieFirstPayment_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateMollieFirstPayment(ctx, c, arg[string](v, "tierId"), arg[string](v, "method"), arg[string](v, "redirectUrl"))
	}},
	"CreateMollieSubscription": {CreateMollieSubscription_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateMollieSubscription(ctx, c, arg[string](v, "tierId"), arg[string](v, "mandateId"), arg[*string](v, "description"))
	}},
	"CreatePayment": {CreatePayment_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreatePayment(ctx, c, arg[CreatePaymentInput](v, "input"))
	}},
	"CreatePushTarget": {CreatePushTarget_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreatePushTarget(ctx, c, arg[string](v, "streamId"), arg[CreatePushTargetInput](v, "input"))
	}},
	"CreateSigningKey": {CreateSigningKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateSigningKey(ctx, c, arg[CreateSigningKeyInput](v, "input"))
	}},
	"CreateStream": {CreateStream_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateStream(ctx, c, arg[CreateStreamInput](v, "input"))
	}},
	"CreateStreamKey": {CreateStreamKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateStreamKey(ctx, c, arg[string](v, "streamId"), arg[CreateStreamKeyInput](v, "input"))
	}},
	"CreateStripeBillingPortal": {CreateStripeBillingPortal_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateStripeBillingPortal(ctx, c, arg[string](v, "returnUrl"))
	}},
	"CreateStripeCheckout": {CreateStripeCheckout_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateStripeCheckout(ctx, c, arg[string](v, "tierId"), arg[string](v, "billingPeriod"), arg[string](v, "successUrl"), arg[string](v, "cancelUrl"))
	}},
	"CreateVodUpload": {CreateVodUpload_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateVodUpload(ctx, c, arg[CreateVodUploadInput](v, "input"))
	}},
	"CreateWebhookEndpoint": {CreateWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CreateWebhookEndpoint(ctx, c, arg[CreateWebhookEndpointInput](v, "input"))
	}},
	"CryptoTopupStatusMutation": {CryptoTopupStatusMutation_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return CryptoTopupStatusMutation(ctx, c, arg[string](v, "topupId"))
	}},
	"DeleteClip": {DeleteClip_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteClip(ctx, c, arg[string](v, "id"))
	}},
	"DeleteDVR": {DeleteDVR_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteDVR(ctx, c, arg[string](v, "dvrHash"))
	}},
	"DeletePushTarget": {DeletePushTarget_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeletePushTarget(ctx, c, arg[string](v, "id"))
	}},
	"DeleteSkipperConversation": {DeleteSkipperConversation_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteSkipperConversation(ctx, c, arg[string](v, "id"))
	}},
	"DeleteStream": {DeleteStream_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteStream(ctx, c, arg[string](v, "id"))
	}},
	"DeleteStreamKey": {DeleteStreamKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteStreamKey(ctx, c, arg[string](v, "streamId"), arg[string](v, "keyId"))
	}},
	"DeleteVodAsset": {DeleteVodAsset_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteVodAsset(ctx, c, arg[string](v, "id"))
	}},
	"DeleteWebhookEndpoint": {DeleteWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DeleteWebhookEndpoint(ctx, c, arg[string](v, "id"))
	}},
	"DisableWebhookEndpoint": {DisableWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return DisableWebhookEndpoint(ctx, c, arg[string](v, "id"))
	}},
	"EnableWebhookEndpoint": {EnableWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return EnableWebhookEndpoint(ctx, c, arg[string](v, "id"))
	}},
	"GetAnalyticsInfraServiceInstancesHealth": {GetAnalyticsInfraServiceInstancesHealth_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetAnalyticsInfraServiceInstancesHealth(ctx, c, arg[*string](v, "serviceId"))
	}},
	"GetApiUsageConnection": {GetApiUsageConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetApiUsageConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "authType"), arg[*string](v, "operationType"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetArtifactEventsConnection": {GetArtifactEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetArtifactEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*string](v, "stage"), arg[*string](v, "contentType"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetArtifactNodeCopies": {GetArtifactNodeCopies_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetArtifactNodeCopies(ctx, c, arg[string](v, "artifactHash"))
	}},
	"GetArtifactStatesConnection": {GetArtifactStatesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetArtifactStatesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*string](v, "contentType"), arg[*string](v, "stage"))
	}},
	"GetBalanceTransactionsConnection": {GetBalanceTransactionsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetBalanceTransactionsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "transactionType"), arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetBillingDetails": {GetBillingDetails_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetBillingDetails(ctx, c)
	}},
	"GetBillingStatus": {GetBillingStatus_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetBillingStatus(ctx, c)
	}},
	"GetBillingTiers": {GetBillingTiers_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetBillingTiers(ctx, c)
	}},
	"GetBufferEventsConnection": {GetBufferEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetBufferEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetCapabilities": {GetCapabilities_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetCapabilities(ctx, c)
	}},
	"GetClientQoeConnection": {GetClientQoeConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClientQoeConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*string](v, "nodeId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetClientQoeSummary": {GetClientQoeSummary_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClientQoeSummary(ctx, c, arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetClip": {GetClip_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClip(ctx, c, arg[string](v, "id"))
	}},
	"GetCluster": {GetCluster_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetCluster(ctx, c, arg[string](v, "id"))
	}},
	"GetClusterBootOps": {GetClusterBootOps_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterBootOps(ctx, c, arg[*string](v, "clusterId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetClusterInvitesConnection": {GetClusterInvitesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterInvitesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "clusterId"))
	}},
	"GetClusterMediaConsent": {GetClusterMediaConsent_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterMediaConsent(ctx, c, arg[string](v, "clusterId"))
	}},
	"GetClusterMediaConsentChange": {GetClusterMediaConsentChange_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterMediaConsentChange(ctx, c, arg[string](v, "clusterId"), arg[string](v, "idempotencyKey"))
	}},
	"GetClusterNodesConnection": {GetClusterNodesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterNodesConnection(ctx, c, arg[string](v, "id"), arg[*ConnectionInput](v, "page"))
	}},
	"GetClusterQoeOps": {GetClusterQoeOps_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterQoeOps(ctx, c, arg[*string](v, "clusterId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetClusterTrafficMatrix": {GetClusterTrafficMatrix_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterTrafficMatrix(ctx, c, arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetClusterWorkload": {GetClusterWorkload_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClusterWorkload(ctx, c, arg[*string](v, "clusterId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetClustersAccessConnection": {GetClustersAccessConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClustersAccessConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetClustersAvailableConnection": {GetClustersAvailableConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClustersAvailableConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetClustersConnection": {GetClustersConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetClustersConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetConnectionEventsConnection": {GetConnectionEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetConnectionEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetConversation": {GetConversation_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetConversation(ctx, c, arg[string](v, "id"))
	}},
	"GetConversationsConnection": {GetConversationsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetConversationsConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetDVRChapter": {GetDVRChapter_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetDVRChapter(ctx, c, arg[string](v, "dvrId"), arg[float64](v, "startMs"), arg[float64](v, "endMs"), arg[*DVRChapterMode](v, "mode"), arg[*int](v, "intervalSeconds"))
	}},
	"GetDailyStats": {GetDailyStats_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetDailyStats(ctx, c, arg[*TimeRangeInput](v, "timeRange"), arg[*int](v, "days"))
	}},
	"GetDiscoverServicesConnection": {GetDiscoverServicesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetDiscoverServicesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "discoverServicesConnectionType"), arg[*string](v, "clusterId"))
	}},
	"GetFederationEventsConnection": {GetFederationEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetFederationEventsConnection(ctx, c, arg[TimeRangeInput](v, "timeRange"), arg[*int](v, "first"), arg[*string](v, "eventType"), arg[*bool](v, "noCache"))
	}},
	"GetFederationSummary": {GetFederationSummary_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetFederationSummary(ctx, c, arg[TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetGeographicDistribution": {GetGeographicDistribution_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetGeographicDistribution(ctx, c, arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*int](v, "topN"))
	}},
	"GetIncident": {GetIncident_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetIncident(ctx, c, arg[string](v, "id"))
	}},
	"GetIncidentsConnection": {GetIncidentsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetIncidentsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*IncidentFilterInput](v, "filter"))
	}},
	"GetInfrastructureNodeMetrics1hConnection": {GetInfrastructureNodeMetrics1hConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetInfrastructureNodeMetrics1hConnection(ctx, c, arg[string](v, "id"), arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetInfrastructureNodeMetricsConnection": {GetInfrastructureNodeMetricsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetInfrastructureNodeMetricsConnection(ctx, c, arg[string](v, "id"), arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetInvoice": {GetInvoice_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetInvoice(ctx, c, arg[string](v, "id"))
	}},
	"GetInvoicesConnection": {GetInvoicesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetInvoicesConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetMarketplaceCluster": {GetMarketplaceCluster_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMarketplaceCluster(ctx, c, arg[string](v, "clusterId"))
	}},
	"GetMarketplaceClustersConnection": {GetMarketplaceClustersConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMarketplaceClustersConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetMediaPlacementChange": {GetMediaPlacementChange_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMediaPlacementChange(ctx, c, arg[MediaPlacementScopeInput](v, "scope"), arg[string](v, "idempotencyKey"))
	}},
	"GetMediaPlacementOptions": {GetMediaPlacementOptions_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMediaPlacementOptions(ctx, c, arg[MediaPlacementScopeInput](v, "scope"), arg[*MediaPlacementOptionsFilter](v, "filter"), arg[*string](v, "after"), arg[*int](v, "first"))
	}},
	"GetMediaPlacementPolicy": {GetMediaPlacementPolicy_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMediaPlacementPolicy(ctx, c, arg[MediaPlacementScopeInput](v, "scope"))
	}},
	"GetMediaRetentionPolicy": {GetMediaRetentionPolicy_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetMediaRetentionPolicy(ctx, c)
	}},
	"GetMessagesConnection": {GetMessagesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMessagesConnection(ctx, c, arg[string](v, "conversationId"), arg[*ConnectionInput](v, "page"))
	}},
	"GetMollieMandates": {GetMollieMandates_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetMollieMandates(ctx, c)
	}},
	"GetMyClusterInvitesConnection": {GetMyClusterInvitesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMyClusterInvitesConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetMySubscriptionsConnection": {GetMySubscriptionsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetMySubscriptionsConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetNetworkStatus": {GetNetworkStatus_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetNetworkStatus(ctx, c)
	}},
	"GetNode": {GetNode_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetNode(ctx, c, arg[string](v, "id"))
	}},
	"GetNodeMetrics1hConnection": {GetNodeMetrics1hConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetNodeMetrics1hConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"), arg[*string](v, "nodeId"), arg[*bool](v, "noCache"))
	}},
	"GetNodeMetricsAggregated": {GetNodeMetricsAggregated_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetNodeMetricsAggregated(ctx, c, arg[*TimeRangeInput](v, "timeRange"), arg[*string](v, "nodeId"), arg[*bool](v, "noCache"))
	}},
	"GetNodeMetricsConnection": {GetNodeMetricsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetNodeMetricsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "nodeId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetNodePerformance5mConnection": {GetNodePerformance5mConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetNodePerformance5mConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "nodeId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetNodesConnection": {GetNodesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetNodesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "clusterId"), arg[*NodeStatus](v, "status"), arg[*string](v, "nodesConnectionType"))
	}},
	"GetOrchestrator": {GetOrchestrator_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetOrchestrator(ctx, c, arg[string](v, "orchAddr"))
	}},
	"GetOrchestratorInstances": {GetOrchestratorInstances_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetOrchestratorInstances(ctx, c, arg[*string](v, "orchAddr"))
	}},
	"GetOrchestratorPerformanceSeries": {GetOrchestratorPerformanceSeries_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetOrchestratorPerformanceSeries(ctx, c, arg[string](v, "orchAddr"), arg[TimeRangeInput](v, "timeRange"), arg[*string](v, "interval"), arg[*string](v, "gatewayId"), arg[*string](v, "resolvedIp"))
	}},
	"GetOrchestratorVantages": {GetOrchestratorVantages_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetOrchestratorVantages(ctx, c, arg[*string](v, "orchAddr"))
	}},
	"GetOrchestratorsConnection": {GetOrchestratorsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetOrchestratorsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "orchAddr"))
	}},
	"GetOverview": {GetOverview_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetOverview(ctx, c, arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetPayment": {GetPayment_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetPayment(ctx, c, arg[string](v, "id"))
	}},
	"GetPaymentsConnection": {GetPaymentsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetPaymentsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "invoiceId"), arg[*string](v, "status"), arg[*string](v, "method"))
	}},
	"GetPendingSubscriptionsConnection": {GetPendingSubscriptionsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetPendingSubscriptionsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "clusterId"))
	}},
	"GetPlayerBootSummary": {GetPlayerBootSummary_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetPlayerBootSummary(ctx, c, arg[*string](v, "streamId"), arg[*string](v, "artifactHash"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetPlayerBootTimeSeries": {GetPlayerBootTimeSeries_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetPlayerBootTimeSeries(ctx, c, arg[*string](v, "streamId"), arg[*string](v, "artifactHash"), arg[*TimeRangeInput](v, "timeRange"), arg[*string](v, "interval"), arg[*bool](v, "noCache"))
	}},
	"GetPrepaidBalance": {GetPrepaidBalance_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetPrepaidBalance(ctx, c)
	}},
	"GetPreviewMediaPlacement": {GetPreviewMediaPlacement_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetPreviewMediaPlacement(ctx, c, arg[PreviewMediaPlacementInput](v, "input"))
	}},
	"GetProcessingUsageConnection": {GetProcessingUsageConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetProcessingUsageConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*string](v, "processType"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetQualityTierDailyConnection": {GetQualityTierDailyConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetQualityTierDailyConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetRebufferingEventsConnection": {GetRebufferingEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetRebufferingEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*string](v, "nodeId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetRecentPullSourceEvents": {GetRecentPullSourceEvents_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetRecentPullSourceEvents(ctx, c, arg[string](v, "id"), arg[*int](v, "limit"))
	}},
	"GetReviewClusterMediaConsentChange": {GetReviewClusterMediaConsentChange_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetReviewClusterMediaConsentChange(ctx, c, arg[ReviewMediaCapacityConsentInput](v, "input"))
	}},
	"GetReviewMediaPlacementChange": {GetReviewMediaPlacementChange_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetReviewMediaPlacementChange(ctx, c, arg[ReviewMediaPlacementChangeInput](v, "input"))
	}},
	"GetRoutingEfficiency": {GetRoutingEfficiency_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetRoutingEfficiency(ctx, c, arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetRoutingEventsConnection": {GetRoutingEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetRoutingEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*string](v, "subjectTenantId"), arg[*string](v, "clusterId"), arg[*bool](v, "noCache"))
	}},
	"GetServiceInstancesConnection": {GetServiceInstancesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetServiceInstancesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "clusterId"), arg[*string](v, "nodeId"), arg[*InstanceStatus](v, "status"))
	}},
	"GetServiceInstancesHealth": {GetServiceInstancesHealth_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetServiceInstancesHealth(ctx, c, arg[*string](v, "serviceId"))
	}},
	"GetSessionQoeSummary": {GetSessionQoeSummary_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSessionQoeSummary(ctx, c, arg[*string](v, "streamId"), arg[*string](v, "artifactHash"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetSessionQoeTimeSeries": {GetSessionQoeTimeSeries_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSessionQoeTimeSeries(ctx, c, arg[*string](v, "streamId"), arg[*string](v, "artifactHash"), arg[*TimeRangeInput](v, "timeRange"), arg[*string](v, "interval"), arg[*bool](v, "noCache"))
	}},
	"GetSigningKey": {GetSigningKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSigningKey(ctx, c, arg[string](v, "id"))
	}},
	"GetSkipperConversation": {GetSkipperConversation_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSkipperConversation(ctx, c, arg[string](v, "id"))
	}},
	"GetSkipperConversations": {GetSkipperConversations_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSkipperConversations(ctx, c, arg[*int](v, "limit"), arg[*int](v, "offset"))
	}},
	"GetSkipperReport": {GetSkipperReport_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSkipperReport(ctx, c, arg[string](v, "id"))
	}},
	"GetSkipperReports": {GetSkipperReports_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetSkipperReports(ctx, c, arg[*int](v, "limit"), arg[*int](v, "offset"))
	}},
	"GetSkipperUnreadReportCount": {GetSkipperUnreadReportCount_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetSkipperUnreadReportCount(ctx, c)
	}},
	"GetStorageEventsConnection": {GetStorageEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStorageEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "assetType"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStorageUsageConnection": {GetStorageUsageConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStorageUsageConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "nodeId"), arg[*string](v, "storageScope"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStream": {GetStream_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStream(ctx, c, arg[string](v, "id"))
	}},
	"GetStreamAnalyticsDailyConnection": {GetStreamAnalyticsDailyConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamAnalyticsDailyConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStreamAnalyticsSummariesConnection": {GetStreamAnalyticsSummariesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamAnalyticsSummariesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[TimeRangeInput](v, "timeRange"), arg[*StreamSummarySortField](v, "sortBy"), arg[*SortOrder](v, "sortOrder"))
	}},
	"GetStreamAnalyticsSummary": {GetStreamAnalyticsSummary_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamAnalyticsSummary(ctx, c, arg[string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetStreamConnectionHourlyConnection": {GetStreamConnectionHourlyConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamConnectionHourlyConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStreamEventsConnection": {GetStreamEventsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamEventsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStreamHealth5mConnection": {GetStreamHealth5mConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamHealth5mConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStreamHealthConnection": {GetStreamHealthConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamHealthConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStreamHealthSummary": {GetStreamHealthSummary_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetStreamHealthSummary(ctx, c, arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetStreamingConfig": {GetStreamingConfig_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetStreamingConfig(ctx, c)
	}},
	"GetTenant": {GetTenant_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetTenant(ctx, c)
	}},
	"GetTenantAnalyticsDailyConnection": {GetTenantAnalyticsDailyConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetTenantAnalyticsDailyConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetTenantUsage": {GetTenantUsage_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetTenantUsage(ctx, c, arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetTopAssets": {GetTopAssets_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetTopAssets(ctx, c, arg[*TimeRangeInput](v, "timeRange"), arg[*int](v, "limit"))
	}},
	"GetTrackListConnection": {GetTrackListConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetTrackListConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetUsageAggregates": {GetUsageAggregates_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetUsageAggregates(ctx, c, arg[TimeRangeInput](v, "timeRange"), arg[*string](v, "granularity"), arg[[]string](v, "usageTypes"))
	}},
	"GetValidateStreamKey": {GetValidateStreamKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetValidateStreamKey(ctx, c, arg[string](v, "streamKey"))
	}},
	"GetViewerGeoHourlyConnection": {GetViewerGeoHourlyConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetViewerGeoHourlyConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetViewerGeographicsConnection": {GetViewerGeographicsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetViewerGeographicsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"))
	}},
	"GetViewerHoursHourlyConnection": {GetViewerHoursHourlyConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetViewerHoursHourlyConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetViewerSessionsConnection": {GetViewerSessionsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetViewerSessionsConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetViewerTimeSeriesConnection": {GetViewerTimeSeriesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetViewerTimeSeriesConnection(ctx, c, arg[*ConnectionInput](v, "page"), arg[string](v, "streamId"), arg[*TimeRangeInput](v, "timeRange"), arg[*string](v, "interval"))
	}},
	"GetVodAsset": {GetVodAsset_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetVodAsset(ctx, c, arg[string](v, "id"))
	}},
	"GetVodRetention": {GetVodRetention_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetVodRetention(ctx, c, arg[string](v, "artifactHash"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetVodRetentionAssets": {GetVodRetentionAssets_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetVodRetentionAssets(ctx, c, arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"), arg[*bool](v, "noCache"))
	}},
	"GetVodUploadStatus": {GetVodUploadStatus_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetVodUploadStatus(ctx, c, arg[string](v, "uploadId"))
	}},
	"GetWebhookDeliveriesConnection": {GetWebhookDeliveriesConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetWebhookDeliveriesConnection(ctx, c, arg[*string](v, "endpointId"), arg[[]WebhookDeliveryStatus](v, "statuses"), arg[*string](v, "eventType"), arg[*string](v, "eventId"), arg[*time.Time](v, "createdAfter"), arg[*time.Time](v, "createdBefore"), arg[*ConnectionInput](v, "page"))
	}},
	"GetWebhookDelivery": {GetWebhookDelivery_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetWebhookDelivery(ctx, c, arg[string](v, "id"))
	}},
	"GetWebhookEndpoint": {GetWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetWebhookEndpoint(ctx, c, arg[string](v, "id"))
	}},
	"GetWebhookEndpointsConnection": {GetWebhookEndpointsConnection_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return GetWebhookEndpointsConnection(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"GetWebhookEventTypes": {GetWebhookEventTypes_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return GetWebhookEventTypes(ctx, c)
	}},
	"ImportVodAsset": {ImportVodAsset_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ImportVodAsset(ctx, c, arg[ImportVodAssetInput](v, "input"))
	}},
	"LinkEmail": {LinkEmail_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return LinkEmail(ctx, c, arg[LinkEmailInput](v, "input"))
	}},
	"LinkWallet": {LinkWallet_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return LinkWallet(ctx, c, arg[WalletLoginInput](v, "input"))
	}},
	"ListArtifacts": {ListArtifacts_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListArtifacts(ctx, c, arg[*StorageArtifactsInput](v, "input"))
	}},
	"ListDVRChapters": {ListDVRChapters_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListDVRChapters(ctx, c, arg[string](v, "dvrId"), arg[*DVRChapterMode](v, "mode"), arg[*int](v, "intervalSeconds"), arg[*float64](v, "rangeStartMs"), arg[*float64](v, "rangeEndMs"), arg[*int](v, "pageSize"), arg[*string](v, "pageToken"))
	}},
	"ListDeveloperTokens": {ListDeveloperTokens_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListDeveloperTokens(ctx, c, arg[*ConnectionInput](v, "page"))
	}},
	"ListPushTargets": {ListPushTargets_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListPushTargets(ctx, c, arg[string](v, "streamId"))
	}},
	"ListSigningKeys": {ListSigningKeys_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListSigningKeys(ctx, c, arg[*string](v, "status"), arg[*ConnectionInput](v, "page"))
	}},
	"ListStreamKeys": {ListStreamKeys_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListStreamKeys(ctx, c, arg[string](v, "streamId"), arg[*ConnectionInput](v, "page"))
	}},
	"ListStreams": {ListStreams_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListStreams(ctx, c, arg[*ConnectionInput](v, "page"), arg[*string](v, "search"))
	}},
	"ListUsageRecords": {ListUsageRecords_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ListUsageRecords(ctx, c, arg[*ConnectionInput](v, "page"), arg[*TimeRangeInput](v, "timeRange"))
	}},
	"MarkSkipperReportsRead": {MarkSkipperReportsRead_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return MarkSkipperReportsRead(ctx, c, arg[[]string](v, "ids"))
	}},
	"OpenMistAdminSession": {OpenMistAdminSession_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return OpenMistAdminSession(ctx, c, arg[OpenMistAdminSessionInput](v, "input"))
	}},
	"PromoteToPaid": {PromoteToPaid_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return PromoteToPaid(ctx, c, arg[string](v, "tierId"))
	}},
	"RefreshStreamKey": {RefreshStreamKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RefreshStreamKey(ctx, c, arg[string](v, "id"))
	}},
	"RejectClusterSubscription": {RejectClusterSubscription_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RejectClusterSubscription(ctx, c, arg[string](v, "subscriptionId"), arg[*string](v, "reason"))
	}},
	"ReplayWebhookDeliveries": {ReplayWebhookDeliveries_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ReplayWebhookDeliveries(ctx, c, arg[string](v, "endpointId"), arg[time.Time](v, "createdAfter"), arg[time.Time](v, "createdBefore"))
	}},
	"ReplayWebhookDelivery": {ReplayWebhookDelivery_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ReplayWebhookDelivery(ctx, c, arg[string](v, "id"))
	}},
	"RequestClusterSubscription": {RequestClusterSubscription_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RequestClusterSubscription(ctx, c, arg[string](v, "clusterId"), arg[*string](v, "inviteToken"))
	}},
	"ResetMediaRetentionOverride": {ResetMediaRetentionOverride_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ResetMediaRetentionOverride(ctx, c, arg[ResetMediaRetentionOverrideInput](v, "input"))
	}},
	"ResolveIncident": {ResolveIncident_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ResolveIncident(ctx, c, arg[string](v, "id"))
	}},
	"ResolveIngestEndpoint": {ResolveIngestEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ResolveIngestEndpoint(ctx, c, arg[string](v, "streamKey"), arg[*MediaIngestProtocol](v, "protocol"))
	}},
	"ResolveViewerEndpoint": {ResolveViewerEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return ResolveViewerEndpoint(ctx, c, arg[string](v, "contentId"), arg[*MediaViewerProtocol](v, "protocol"))
	}},
	"RevokeClusterInvite": {RevokeClusterInvite_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RevokeClusterInvite(ctx, c, arg[string](v, "inviteId"))
	}},
	"RevokeDeveloperToken": {RevokeDeveloperToken_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RevokeDeveloperToken(ctx, c, arg[string](v, "id"))
	}},
	"RevokeSigningKey": {RevokeSigningKey_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RevokeSigningKey(ctx, c, arg[string](v, "id"))
	}},
	"RotateWebhookEndpointSecret": {RotateWebhookEndpointSecret_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return RotateWebhookEndpointSecret(ctx, c, arg[string](v, "id"), arg[*bool](v, "revokePrevious"))
	}},
	"SendMessage": {SendMessage_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SendMessage(ctx, c, arg[SendMessageInput](v, "input"))
	}},
	"ServerInfo": {ServerInfo_Operation, func(ctx context.Context, c *Client, _ vars) (any, error) {
		return ServerInfo(ctx, c)
	}},
	"SetMediaRetentionPolicy": {SetMediaRetentionPolicy_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SetMediaRetentionPolicy(ctx, c, arg[SetMediaRetentionPolicyInput](v, "input"))
	}},
	"SetNodeMode": {SetNodeMode_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SetNodeMode(ctx, c, arg[SetNodeModeInput](v, "input"))
	}},
	"SetPlaybackPolicy": {SetPlaybackPolicy_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SetPlaybackPolicy(ctx, c, arg[SetPlaybackPolicyInput](v, "input"))
	}},
	"SetPreferredCluster": {SetPreferredCluster_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SetPreferredCluster(ctx, c, arg[string](v, "clusterId"))
	}},
	"SetStreamRetentionOverrides": {SetStreamRetentionOverrides_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SetStreamRetentionOverrides(ctx, c, arg[SetStreamRetentionOverridesInput](v, "input"))
	}},
	"StartDVR": {StartDVR_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return StartDVR(ctx, c, arg[string](v, "streamId"))
	}},
	"StopDVR": {StopDVR_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return StopDVR(ctx, c, arg[string](v, "dvrHash"))
	}},
	"SubmitX402Payment": {SubmitX402Payment_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SubmitX402Payment(ctx, c, arg[string](v, "payment"), arg[*string](v, "resource"))
	}},
	"SubscribeToCluster": {SubscribeToCluster_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return SubscribeToCluster(ctx, c, arg[string](v, "clusterId"))
	}},
	"TestPlaybackAccess": {TestPlaybackAccess_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return TestPlaybackAccess(ctx, c, arg[TestPlaybackAccessInput](v, "input"))
	}},
	"TestWebhookEndpoint": {TestWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return TestWebhookEndpoint(ctx, c, arg[string](v, "id"))
	}},
	"UnlinkWallet": {UnlinkWallet_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UnlinkWallet(ctx, c, arg[string](v, "walletId"))
	}},
	"UnsubscribeFromCluster": {UnsubscribeFromCluster_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UnsubscribeFromCluster(ctx, c, arg[string](v, "clusterId"))
	}},
	"UpdateBillingDetails": {UpdateBillingDetails_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateBillingDetails(ctx, c, arg[UpdateBillingDetailsInput](v, "input"))
	}},
	"UpdateClusterMarketplace": {UpdateClusterMarketplace_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateClusterMarketplace(ctx, c, arg[string](v, "clusterId"), arg[UpdateClusterMarketplaceInput](v, "input"))
	}},
	"UpdateMediaRetention": {UpdateMediaRetention_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateMediaRetention(ctx, c, arg[UpdateMediaRetentionInput](v, "input"))
	}},
	"UpdatePushTarget": {UpdatePushTarget_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdatePushTarget(ctx, c, arg[string](v, "id"), arg[UpdatePushTargetInput](v, "input"))
	}},
	"UpdateSkipperConversation": {UpdateSkipperConversation_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateSkipperConversation(ctx, c, arg[string](v, "id"), arg[string](v, "title"))
	}},
	"UpdateStream": {UpdateStream_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateStream(ctx, c, arg[string](v, "id"), arg[UpdateStreamInput](v, "input"))
	}},
	"UpdateTenant": {UpdateTenant_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateTenant(ctx, c, arg[UpdateTenantInput](v, "input"))
	}},
	"UpdateWebhookEndpoint": {UpdateWebhookEndpoint_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return UpdateWebhookEndpoint(ctx, c, arg[string](v, "id"), arg[UpdateWebhookEndpointInput](v, "input"))
	}},
	"WalletLogin": {WalletLogin_Operation, func(ctx context.Context, c *Client, v vars) (any, error) {
		return WalletLogin(ctx, c, arg[WalletLoginInput](v, "input"))
	}},
}

// subscriptionCalls subscribes to every generated subscription through its
// Subscribe function with the fixture's variables.
var subscriptionCalls = map[string]func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error]{
	"LiveConnectionEvents": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveConnectionEvents(ctx, sc, arg[*string](v, "streamId")))
	},
	"LiveConversationUpdates": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveConversationUpdates(ctx, sc, arg[*string](v, "conversationId")))
	},
	"LiveFirehose": func(ctx context.Context, sc *SubscriptionClient, _ vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveFirehose(ctx, sc))
	},
	"LiveIncidentUpdates": func(ctx context.Context, sc *SubscriptionClient, _ vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveIncidentUpdates(ctx, sc))
	},
	"LiveMessageReceived": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveMessageReceived(ctx, sc, arg[string](v, "conversationId")))
	},
	"LiveProcessingEvents": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveProcessingEvents(ctx, sc, arg[*string](v, "streamId")))
	},
	"LiveStorageEvents": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveStorageEvents(ctx, sc, arg[*string](v, "streamId")))
	},
	"LiveStreamEvents": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveStreamEvents(ctx, sc, arg[*string](v, "streamId")))
	},
	"LiveSystemHealth": func(ctx context.Context, sc *SubscriptionClient, _ vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveSystemHealth(ctx, sc))
	},
	"LiveTrackListUpdates": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveTrackListUpdates(ctx, sc, arg[string](v, "streamId")))
	},
	"LiveViewerMetrics": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeLiveViewerMetrics(ctx, sc, arg[string](v, "streamId")))
	},
	"SkipperChat": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeSkipperChat(ctx, sc, arg[SkipperChatInput](v, "input")))
	},
	"TenantEvents": func(ctx context.Context, sc *SubscriptionClient, v vars) iter.Seq2[any, error] {
		return anyEvents(SubscribeTenantEvents(ctx, sc, arg[[]string](v, "types"), arg[*string](v, "streamId")))
	},
}
